stages:
  - install
  - build
  - deploy

cache:
  paths:
    - node_modules/

install:
  stage: install
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/
  only:
    - develop

build:
  stage: build
  script:
    - CI=false npm run build
  artifacts:
    paths:
      - build/
  only:
    - develop

deploy:
  stage: deploy
  script: cp -rv build/* /var/www/boxapp/app/
  only:
    - develop
